# Nama workflow yang akan muncul di tab "Actions" GitHub
name: Deploy to Production Server

# Pemicu (Trigger)
# Workflow ini akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches:
      - main

# Pekerjaan (Jobs)
# Kita hanya punya satu pekerjaan bernama 'deploy'
jobs:
  deploy:
    # Mesin virtual yang akan digunakan
    runs-on: ubuntu-latest

    # Langkah-langkah yang akan dijalankan
    steps:
      # Langkah 1: Checkout kode dari repositori
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Setup lingkungan Go
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.23' # Sesuaikan dengan versi Go Anda

      # Langkah 3: Sinkronisasi dependensi
      - name: Go Tidy
        run: go mod tidy

      # Langkah 4: Build aplikasi Go untuk server Linux
      - name: Build Go App
        run: CGO_ENABLED=0 GOOS=linux go build -o kredit-app ./cmd/api/main.go

      # Langkah 5: Salin file binary dan migrasi ke server
      - name: Copy files to server
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "kredit-app,migrations" # File dan folder yang akan disalin
          target: "~/app/kredit-plus"      # Tujuan di server

      # Langkah 6: Jalankan perintah deployment di server
      - name: Execute deployment commands
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app/kredit-plus

            # Jalankan migrasi database
            migrate -database "${{ secrets.DB_MIGRATE_URL }}" -path migrations up

            # Restart service aplikasi menggunakan systemd
            sudo systemctl restart kredit-plus

            # Cek status untuk memastikan service berjalan
            sudo systemctl status kredit-plus
